const data = {
  "Cryptid": { "Talisman": "REQUIRE" },
  "Steamodded (>=1.0.0~BETA-0827)": { "Cryptid": "REQUIRE", },
  "Talisman (>=2.2.0a)": { "Cryptid": "REQUIRE", },
  "Cryptlib": { "Cryptid": "PROVIDES", },
  "AntePreview (>= 2.0.0~0c16a) (<<3.0.0)": { "Cryptid": "CONFLICT", },
  "Cartomancer (<= 4.11)": { "Cryptid": "CONFLICT", },
  "Aikoyori's Shenanigans": { "Lovely (>=0.8.0)": "REQUIRE", "Steamodded (>=1.0.0~BETA-1016c)": "REQUIRE", "Balatro (>=1.0.1o)": "REQUIRE", },
  "AMY's Waifus": { "Malverk": "REQUIRE", },
  "BalaQuints": { "Malverk (>=1.1.3~)": "REQUIRE", },
  "Mobile Compatibility": {},
  "Shenanigans's Decks": { "Steamodded (>=1.0.0~BETA-1016c)": "REQUIRE", },
  "Card Sleeves": { "GRM (<=0.9.5)": "CONFLICT", "VNBalatro (<=1.3.0)": "CONFLICT", "SKHDecks (<=1.2.2)": "CONFLICT", "MoreFluff (<=1.0.3)": "CONFLICT", "Steamodded (>=1.0.0~ALPHA-1424a)": "REQUIRE", "Lovely (>=0.6.0)": "REQUIRE" },
  "Galdur": { "Steamodded (>=1.0.0~ALPHA-1217b)":"REQUIRES", },
  "HotPotato": { "Steamodded (>=1.0.0~BETA-1016c)":"REQUIRES", "SlayTheJokers":"CONFLICT", },
  "JokerDisplay": { "Steamodded (>=1.0.0~BETA-0624a)":"REQUIRES", },
  "Kino": {"Blockbuster-Counters":"PROVIDES", "Blockbuster-Spellcasting":"PROVIDES", "Blockbuster-ValueManipulation":"PROVIDES", "Steamodded (>=1.0.0~BETA-0827a)":"REQUIRES", "Lovely (>=0.8.0)":"REQUIRES" },
  "Next Ante Preview": {"Cryptid (<<0.5.5a~dev)":"CONFLICT","Multiplayer (<<0.2.1)":"CONFLICT","Ortalab":"CONFLICT","StrangeLib (<<2.1.2)": "CONFLICT", "VirtualizedMultiplayer":"CONFLICT", "Steamodded (>=1.0.0~ALPHA-1021a)": "REQUIRES", },
  "Paperback": {"Steamodded (>=1.0.0~BETA-0711a)": "REQUIRES", "Lovely (>=0.7.1)":"REQUIRES", },
  "Partner": {"Steamodded (>=1.0.0~BETA-0323b)":"REQUIRES", "Lovely (>=0.6.0)":"REQUIRES", },
  "Pokermon": {"Steamodded (>=1.0.0~BETA-0711a)":"REQUIRES", "Lovely (>=0.7.0)":"REQUIRES", },
  "Steammodded": {"Thunderstore-lovely-0.7.1":"REQUIRES", },
  "Sticky Fingers": {"Steamodded (>=1.*)":"REQUIRES", "Lovely (>=0.6)":"REQUIRES", },
  "Too Many Jokers": {"Steamodded (>=1.0.0~BETA-0715a)":"REQUIRES", },
  "ZokersModMenu": {"Steamodded-Steamodded-0.9.8":"REQUIRES", },

};
